image: docker:latest

stages:
  - build
  - prod
  - stable
  - deploy

before_script:
  - export CONTAINER_IMAGE_NAME="theykk/${CI_PROJECT_NAME}"
  - export KUBE_CONFIG="${CI_K8S_CONFIG}"
  - export CONTAINER_GENERAL_IMAGE="${CONTAINER_IMAGE_NAME}:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
  - export CONTAINER_TAGGED_IMAGE="${CONTAINER_IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
  - export CONTAINER_LATEST_IMAGE="${CONTAINER_IMAGE_NAME}:latest"
 
variables:
  DOCKER_DRIVER: overlay

services:
    - docker:dind

build:
  stage: build
  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - docker build --pull -t $CONTAINER_GENERAL_IMAGE .
    - docker push $CONTAINER_GENERAL_IMAGE
  only:
    - branches
  except:
    - master

prod:
  stage: prod
  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - docker build --pull -t $CONTAINER_GENERAL_IMAGE .
    - docker tag  $CONTAINER_GENERAL_IMAGE $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_GENERAL_IMAGE
  only:
    - master

stable:
  stage: stable
  script:
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - docker build --pull -t $CONTAINER_TAGGED_IMAGE .
    - docker push $CONTAINER_TAGGED_IMAGE
  only:
    - tags

deploy_dev:
  stage: deploy
  image: alpine
  environment:
    name: master
  script:
    - apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl rolling-update my-nginx --image=$CONTAINER_LATEST_IMAGE  --namespace default --image-pull-policy=Always
