apiVersion: v1
kind: Service
metadata:
  name: theykk-me-nginxsvc
  labels:
    app: theykk-me-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 443
    protocol: UDP
    name: quick
  selector:
    app: theykk-me-nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: theykk-me-nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: theykk-net-tls-prod
      containers:
      - name: nginx-https
        image: theykk/me
        ports:
        - containerPort: 443
        - containerPort: 80        
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: theykk-me-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 

spec:
  tls:
  - hosts:
    - theykk.net
    secretName: theykk-net-tls-prod
  rules:
  - host: theykk.net
    http:
      paths:
      - path: /
        backend:
          serviceName: theykk-me-nginxsvc
          servicePort: http
