apiVersion: apps/v1
kind: Deployment
metadata:
  name: theykk-me-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theykk-me-nginx
  template:
    metadata:
      labels:
        app: theykk-me-nginx
    spec:
      serviceAccountName: httpbin
      volumes:
      - name: secret-volume
        secret:
          secretName: theykkcert
      containers:
      - name: theykk-me-nginx
        image: theykk/me:com_299f7fae96ab7bb8558b1f3cdc9fb31c6235e216
        ports:
        - containerPort: 443
        - containerPort: 80        
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: theykk-me-nginx
  labels:
    app: theykk-me-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: theykk-me-nginx
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: theykk-com-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "theykk.com"
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - "theykk.com"
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: theykk-com
spec:
  hosts:
  - "theykk.com"
  gateways:
  - theykk-com-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: theykk-me-nginx